---

- name: restart php-fpm
  action: service name="php{{ php_fpm_php_version }}-fpm" state=restarted

- name: reload php-fpm
  action: service name="php{{ php_fpm_php_version }}-fpm" state=reloaded
