---
# Install php7-fpm

- name: Add php 7.0 repository
  apt_repository: repo='ppa:ondrej/php-7.0' state=present update_cache=yes validate_certs=no

- name: Install PHP 7.0 and basic extensions
  action: apt pkg={{item}} state=latest
  with_items:
    - php7.0-common
    - php7.0-fpm
    - php7.0-cli
    - php7.0-pgsql
    - php7.0-json
    - php7.0-intl

- name: Install xdebug extension
  action: apt pkg={{item}} state=latest
  when: php_fpm_xdebug_enabled == 1
  with_items:
    - php-xdebug

- name: Configure xdebug for remote debugging
  lineinfile: dest=/etc/php/mods-available/xdebug.ini line={{ item }}
  when: php_fpm_xdebug_enabled == 1
  with_items:
    - "xdebug.max_nesting_level=300"
    - "xdebug.remote_enable=1"
    - "xdebug.remote_host={{ php_fpm_xdebug_remote_host }}"

- name: Install composer
  shell: php -r "readfile('https://getcomposer.org/installer');" | php && mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  when: php_fpm_install_composer == 1
