---
# Install PHP

- name: Register php reposiory
  apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes

- name: Install PHP and basic extensions
  action: apt pkg={{item}} state=latest
  with_items:
    - php{{ php_fpm_php_version }}-cli
    - php{{ php_fpm_php_version }}-fpm
    - php{{ php_fpm_php_version }}-curl
    - php{{ php_fpm_php_version }}-dom
    - php{{ php_fpm_php_version }}-mbstring

- name: Install xdebug extension
  apt: pkg={{item}} state=latest
  when: php_fpm_xdebug_enabled == 1
  with_items:
    - php{{ php_fpm_php_version }}-xdebug

- name: Configure xdebug for remote debugging
  lineinfile: dest=/etc/php/{{ php_fpm_php_version }}/mods-available/xdebug.ini line={{ item }}
  when: php_fpm_xdebug_enabled == 1
  with_items:
    - "xdebug.max_nesting_level=300"
    - "xdebug.remote_enable=1"
    - "xdebug.remote_host={{ php_fpm_xdebug_remote_host }}"

- name: Uncomment reload signal in php-fpm init
  lineinfile:
    backup=yes
    state=present
    dest=/etc/init/php{{ php_fpm_php_version }}-fpm.conf
    regexp='reload signal USR2'
    line='reload signal USR2'
